- hosts: localhost
  connection: local
  vars_files:
    - private.yml

  tasks:
    - name: Gather vmware host facts
      vmware_host_facts:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
      register: host_facts
      delegate_to: localhost

    - name: debug
      debug:
       msg: "{{ host_facts }}"
