- hosts: all

  vars:
    ansible_password: "{{ password }}"
 
  tasks:
     - name: Serviceのインストール
       yum: name="{{ service }}" state=latest
       
     - name: Serviceの起動設定
       service: name="{{ service }}" state=started enabled=yes
